# -*- coding: utf-8 -*-
"""ЛР2_МН_Чайка_Завдання1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eq9DHW40DreZMlv67JW9vgqX4KqaCz4R
"""

import numpy as np
import pandas as pd
import requests

"""Завдання 1 Чайка О.О. Був присутній на парі."""

url = "https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)"
html = requests.get(url, headers={"User-Agent": "Mozilla/5.0"}).text

tables = pd.read_html(html)   # зчитати всі таблиці
df = tables[2]                # потрібна таблиця (може змінюватись!), номери не є сталими!
df.head()

df.info()

df.columns = (df.columns
              .str.replace(r'(?:\s*\[\d+\])+', '', regex=True)  # прибрати [1], [6], ...
              .str.replace('Country/Territory', 'Country', regex=False))
df

df.isnull().sum()

df['IMF (2025)'] = pd.to_numeric(df['IMF (2025)'], errors='coerce')
df['World Bank (2022–24)'] = pd.to_numeric(df['World Bank (2022–24)'], errors='coerce')
df['United Nations (2023)'] = pd.to_numeric(df['United Nations (2023)'], errors='coerce')

df.head(10)

df.isnull().sum()

df.iloc[:, 1:] = df.iloc[:, 1:].apply(lambda x: x.fillna(x.mean()), axis=1)

df.isnull().sum()

df

df.duplicated().sum()

df.describe()

# Count difference between IMF_Forecast and WB_Estimate for each country
df['IMF_WB_Diff'] = abs(df['IMF (2025)'] - df['World Bank (2022–24)'])

# Find which country has the largest difference between IMF and WB
max_diff = df['IMF_WB_Diff'].max()

country = df[df['IMF_WB_Diff'] == max_diff]['Country'].values[0]
print(f'{country} has the largest difference between IMF and WB: {max_diff}')

df.head(10)

# Calculate correlation between IMF and WB and UN
cor_IMF_WB = df['IMF (2025)'].corr(df['World Bank (2022–24)'])
cor_IMF_UN = df['IMF (2025)'].corr(df['United Nations (2023)'])
cor_WB_UN = df['World Bank (2022–24)'].corr(df['United Nations (2023)'])

print(f'Correlation between IMF and WB: {cor_IMF_WB}')
print(f'Correlation between IMF and UN: {cor_IMF_UN}')
print(f'Correlation between  WB and UN: {cor_WB_UN}')

# Find highest correlation
max_cor = max(cor_IMF_WB, cor_IMF_UN, cor_WB_UN)
if max_cor == cor_IMF_WB:
    print('IMF and WB have the highest correlation')
elif max_cor == cor_IMF_UN:
    print('IMF and UN have the highest correlation')
else:
    print('WB and UN have the highest correlation')

mean_IMF = df['IMF (2025)'].mean()
mean_IMF

mean_WB = df['World Bank (2022–24)'].mean()
mean_WB

mean_UN = df['United Nations (2023)'].mean()
mean_UN

# Find standard deviation for each row
df['std'] = df.iloc[:, 1:].std(axis=1)

# Find country with the highest standard deviation
max_std = df['std'].max()
country = df[df['std'] == max_std]['Country'].values[0]
print(f'{country} has the highest standard deviation: {max_std}')

df.head(10)

max_IMF = df['IMF (2025)'].max(); min_IMF = df['IMF (2025)'].min()
max_WB = df['World Bank (2022–24)'].max(); min_WB = df['World Bank (2022–24)'].min()
max_UN = df['United Nations (2023)'].max(); min_UN = df['United Nations (2023)'].min()

print(f'Max IMF: {max_IMF}, Min IMF: {min_IMF}')
print(f'Max WB: {max_WB}, Min WB: {min_WB}')
print(f'Max UN: {max_UN}, Min UN: {min_UN}')

import matplotlib.pyplot as plt

# Build a histogram of IMF_Forecast
plt.hist(df['IMF (2025)'], bins=10)
plt.title('IMF (2025)')
plt.xlabel('GDP')
plt.ylabel('Number of countries')
plt.show()

# Calculate share of world GDP for each country for each year
df['IMF_Share'] = df['IMF (2025)'] / df['IMF (2025)'].sum()
df['WB_Share'] = df['World Bank (2022–24)'] / df['World Bank (2022–24)'].sum()
df['UN_Share'] = df['United Nations (2023)'] / df['United Nations (2023)'].sum()

df.head(10)

# Find top 10 countries with the most significant change in share of world GDP between IMF and UN
df['IMF_UN_Diff'] = abs(df['IMF_Share'] - df['UN_Share'])
df_top10 = df.nlargest(10, 'IMF_UN_Diff')
df_top10

for index, row in df_top10.iterrows():
    plt.plot(row[['UN_Share', 'WB_Share', 'IMF_Share']], label=row['Country'])

plt.title('Share of world GDP')
plt.xlabel('Year')
plt.xticks(ticks=[0, 1, 2], labels=['2022', '2023', '2024'])
plt.ylabel('Share')
plt.legend()
plt.grid()
plt.show()