# -*- coding: utf-8 -*-
"""ЛР_1_МН_Матриці_частини_1+доп

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uIvBSvqSEaM76rdxs0pHPIAfiR3W-YY9
"""

import numpy as np
np.__version__

#1 Я був на уроці і виконував все за Вами
matrix = np.random.randint(1, 3, size=(3, 3))
matrix

#2
det = np.linalg.det(matrix)
det

product = np.prod(matrix)
product

prod_1=np.prod(matrix[0])
prod_2=np.prod(matrix[1])
prod_3=np.prod(matrix[2])
prod_1*prod_2*prod_3

sum = np.sum(matrix)

sum

max_element=np.max(matrix)
print("Найбільший елемент матриці:", max_element)
min_element = np.min(matrix)
print("Найменший елемент матриці:", min_element)

mean=np.mean(matrix)
print("Середнє значення елементів матриці:",mean)

sqrt_matrix=np.sqrt(matrix)
print("Матриця квадратних коренів:")
print(sqrt_matrix)

row_sums=np.sum(matrix,axis=1).reshape(-1,1)
print("Сума елементів кожного рядка:")
print(row_sums)

vector = np.random.randint(0, 10, size=25)

print("початковий вектор:")
print(vector)

sorted_vector = np.sort(vector)[::-1]

print("Вектор сортування за спаданням")
print(sorted_vector)

from scipy import stats
mode = stats.mode(vector)

median = np.median(vector)
mean = np.median(vector)
max_value = np.max(vector)
min_value = np.min(vector)

print("Мода:", mode)
print("Медіана:", median)
print("Середнє:", mean)
print("Макс значення", max_value)
print("Мін значення", min_value)

matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

print("Матриця 1:")
print(matrix1)

print("Матриця 2:")
print(matrix2)

matrix_sum = matrix1 + matrix2
matrix_diff = matrix1 - matrix2
matrix_product = matrix1 * matrix2
matrix_division = np.divide(matrix1, matrix2, where=(matrix2!=0))

print()
print(matrix_sum)

print(matrix_diff)

print(matrix_product)

#12
x = np.arange(9.0)
x

x1 = x.reshape((3, 3))
x1

x2 = np.arange(3.0)
x2

np.multiply(x1, x2)

#13
x1 = np.arange(6)
x1

np.power(x1, 3)

#14
x2 = np.array([1, 2, 3, 3, 2, 1])
x1 = np.arange(6)
x1 ** x2

#1
vector = np.array([1, 2, 3, 4, 5])

vector

#2
v1 = np.matrix([1, 2, 3, 4, 5])

v1

v2 = v1.T
v2

#3
v = np.array([1, 2, 3, 4, 5])
v

v[::-1]

v = np.flip(v)
print(v)

#7
print(np.mean(v))

#8
np.max(v)
print(np.max(x))
print(np.min(x))

#9
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

v1

v2

np.dot(v1,v2)

#10
v = np.array([1, 2, 3, 4, 5])
norm = np.linalg.norm(v)
print(norm)
v/norm

#11
v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])

np.dot(v1, v2)

#12
v = np.array([1, 2, 3, 2, 4, 5, 3])

np.unique(v)

#14
vector = np.array([1, 2, 3, 4, 5])
length = np.linalg.norm(vector)
length

np.isclose(length, 5)

#15
a = np.random.randint(0, 11, (3, 3))
a

#16
np.linalg.det(a)

#17
np.linalg.inv(a)

#18
a = np.array([[1, 3, -4], [0, 2, -3], [-2, 2, 5]])
b = np.array([5, 3, 4])

x = np.linalg.solve(a, b)
print(x)

inv_a = np.linalg.inv(a)
x1 = inv_a.dot(b)
print(x1)