# -*- coding: utf-8 -*-
"""ЛР_2_МН_Завдання2_Чайка

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lOa7DpK7a7KFLBPNRwsI4fzwNfrjEeAB

Чайка О.О. був на парі
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import kagglehub
import os

# Download latest version
path = kagglehub.dataset_download("mahmoudshogaa/titanic-dataset")

print("Path to dataset files:", path)

df = pd.read_csv(os.path.join(path, "titanic.csv"))

df.head()

"""**PassengerId:** A unique identifier for each passenger.

**Survived:** This column indicates whether a passenger survived (1) or did not survive (0).

**Pclass** (Ticket class): A proxy for socio-economic status, with 1 being the highest class and 3 the lowest.

**Name:** The name of the passenger.

**Sex:** The gender of the passenger.

**Age:** The age of the passenger. (Note: There might be missing values in this column.)

**SibSp:** The number of siblings or spouses the passenger had aboard the Titanic.

**Parch:** The number of parents or children the passenger had aboard the Titanic.

**Ticket:** The ticket number.

**Fare:** The amount of money the passenger paid for the ticket.
"""

df.info()

df.isnull().sum()

df['Age'] = df['Age'].fillna(df['Age'].median(skipna=True))

df.drop(['Cabin'], axis=1, inplace=True) # вирішили видалити колонку

df.isnull().sum()

# Clean the dataset of unnecessary columns
df = df[['Survived', 'Pclass', 'Sex', 'Age', 'Fare']]

df.head()

df['Sex'].value_counts()

# Convert categorical data to numerical data
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})

print(f'Data types of the dataset:\n{df.dtypes}')

df.describe()

df.isnull().sum()

df.head()

df.tail()

# Calculate share of survivors by sex
male_survival_rate = df[(df['Sex'] == 0) & (df['Survived'] == 1)].shape[0] / df[df['Sex'] == 0].shape[0]
female_survival_rate = df[(df['Sex'] == 1) & (df['Survived'] == 1)].shape[0] / df[df['Sex'] == 1].shape[0]

print(f'Share of survived males {male_survival_rate * 100:.2f}%')
print(f'Share of survived females {female_survival_rate * 100:.2f}%')

print(f'Correlation between sex and survival: {df["Sex"].corr(df["Survived"])}')

class1_surv_rate = df[(df['Pclass'] == 1) & (df['Survived'] == 1)].shape[0] / df[df['Pclass'] == 1].shape[0]
class2_surv_rate = df[(df['Pclass'] == 2) & (df['Survived'] == 1)].shape[0] / df[df['Pclass'] == 2].shape[0]
class3_surv_rate = df[(df['Pclass'] == 3) & (df['Survived'] == 1)].shape[0] / df[df['Pclass'] == 3].shape[0]

print(f'Share of survived class 1 passengers {class1_surv_rate * 100:.2f}%')
print(f'Share of survived class 2 passengers {class2_surv_rate * 100:.2f}%')
print(f'Share of survived class 3 passengers {class3_surv_rate * 100:.2f}%')

survived_mean_age = df[df['Survived'] == 1]['Age'].mean()
not_survived_mean_age = df[df['Survived'] == 0]['Age'].mean()

print(f'Mean age of survived passengers: {survived_mean_age:.2f}')
print(f'Mean age of not survived passengers: {not_survived_mean_age:.2f}')

# Separate dataset in 4 buckets by Fare sorted in ascending order
df['Fare_Category'] = pd.qcut(df['Fare'], 6, labels=False)

# Find share of survivors in each bucket
for i in range(6):
    surv_rate = df[(df['Fare_Category'] == i) & (df['Survived'] == 1)].shape[0] / df[df['Fare_Category'] == i].shape[0]
    print(f'Share of survived passengers in bucket {i}: {surv_rate * 100:.2f}%')

# Find median fare for the class
for i in range(1, 4):
    median_fare = df[df['Pclass'] == i]['Fare'].median()
    print(f'Median fare for class {i}: {median_fare:.2f}')

# Combine the data into a single DataFrame
df_survived = df[df['Survived'] == 1][['Age']]
df_survived['Status'] = 'Survived'

df_not_survived = df[df['Survived'] == 0][['Age']]
df_not_survived['Status'] = 'Not Survived'

df_combined = pd.concat([df_survived, df_not_survived])

# Plot the histogram with hue
sns.histplot(data=df_combined, x='Age', hue='Status', bins=20)

df.corr()